/**
 * Ingest Types
 *
 * Public type exports for the ingest package.
 */

// Document types
export type {
  DocumentType,
  ElementType,
  DocumentMetadata,
  ChunkMetadata,
  Chunk,
  Element,
  BoundingBox,
  TableData,
  ImageData,
  EnrichmentData,
  Entity,
  SentimentResult,
  ProcessedDocument,
  ProcessingError,
  DocumentInput,
} from './document.types.js';

// Parser types
export type {
  ParserCapabilities,
  ParserOptions,
  ParseResult,
  Parser,
  OCREngineInterface,
  PDFParserOptions,
  DOCXParserOptions,
  HTMLParserOptions,
  MarkdownParserOptions,
  CSVParserOptions,
  ExcelParserOptions,
  ParserRegistryConfig,
} from './parser.types.js';

// Chunking types
export type {
  ChunkingStrategy,
  TokenCounter,
  ChunkingOptions,
  FixedChunkingOptions,
  SemanticChunkingOptions,
  RecursiveChunkingOptions,
  HierarchicalChunkingOptions,
  SentenceChunkingOptions,
  ParagraphChunkingOptions,
  SlidingWindowChunkingOptions,
  Chunker,
  ChunkResult,
  OverlapConfig,
  BoundaryDetector,
  BoundaryType,
  ChunkIndex,
  ChunkerRegistryConfig,
} from './chunking.types.js';

// Extraction types
export type {
  TableExtractionOptions,
  TableOutputFormat,
  ExtractedTable,
  TableStructure,
  MergedCellRegion,
  ColumnType,
  ImageExtractionOptions,
  ImageOutputFormat,
  ExtractedImage,
  ImageType,
  ColorAnalysis,
  MetadataExtractionOptions,
  ExtendedMetadata,
  DocumentStatistics,
  LinkExtractionOptions,
  ExtractedLink,
  LinkPosition,
  FormField,
  Annotation,
  Extractor,
  TableExtractor,
  ImageExtractor,
  MetadataExtractor,
} from './extraction.types.js';

// OCR types
export type {
  OCREngineType,
  OCRConfig,
  PageSegmentationMode,
  OCRPreprocessingOptions,
  OCRResult,
  OCRBlock,
  OCRBlockType,
  OCRElement,
  OCRFontInfo,
  OCREngine,
  OCROptions,
  TesseractConfig,
  GoogleVisionConfig,
  GoogleVisionFeature,
  AWSTextractConfig,
  AzureVisionConfig,
  OCREngineFactoryConfig,
  OCRQualityMetrics,
} from './ocr.types.js';

// Cleaning types
export type {
  CleaningOperation,
  CleaningConfig,
  CleaningHandler,
  CleaningOptions,
  CleaningResult,
  CleaningChange,
  TextNormalizer,
  NormalizationOptions,
  DeduplicationOptions,
  DeduplicationResult,
  DuplicateGroup,
  ContentFilter,
  ContentFilterOptions,
  PIIType,
  PIIDetectionResult,
  PIIInstance,
  HeaderFooterOptions,
  DetectedHeaderFooter,
  TextCleaner,
} from './cleaning.types.js';

// Enrichment types
export type {
  EnrichmentType,
  EnrichmentConfig,
  EnrichmentHandler,
  EntityExtractionConfig,
  EntityType,
  ExtendedEntity,
  KeywordExtractionConfig,
  KeywordExtractionMethod,
  ExtractedKeyword,
  SummarizationConfig,
  SummaryType,
  SummaryResult,
  SentimentConfig,
  ExtendedSentimentResult,
  EmotionResult,
  EmotionType,
  SentimentSegment,
  TopicConfig,
  TopicMethod,
  TopicResult,
  ClassificationConfig,
  ClassificationResult,
  EmbeddingConfig,
  EmbeddingResult,
  RelationConfig,
  ExtractedRelation,
  Enricher,
  EnrichmentResult,
} from './enrichment.types.js';

// Storage types
export type {
  StorageAdapterType,
  StorageConfig,
  DocumentStorage,
  ChunkStorage,
  VectorStorage,
  ListOptions,
  ListResult,
  DocumentQuery,
  VectorSearchOptions,
  VectorSearchResult,
  VectorIndexStats,
  MemoryStorageOptions,
  FileStorageOptions,
  SQLiteStorageOptions,
  PostgresStorageOptions,
  MongoDBStorageOptions,
  RedisStorageOptions,
  PineconeStorageOptions,
  WeaviateStorageOptions,
  QdrantStorageOptions,
  ChromaStorageOptions,
  StorageFactoryConfig,
} from './storage.types.js';

// Pipeline types
export type {
  PipelineStage,
  PipelineConfig,
  ExtractionConfig,
  ChunkingConfig,
  EmbeddingPipelineConfig,
  ErrorHandlingConfig,
  PipelineCallbacks,
  CustomStageHandler,
  PipelineContext,
  PipelineLogger,
  PipelineProgress,
  PipelineError,
  PipelineResult,
  Pipeline,
  PipelineValidationResult,
  IngesterConfig,
  WatchModeConfig,
  Ingester,
  DirectoryIngestOptions,
  IngesterStatus,
  BatchOptions,
  StreamOptions,
  PipelineBuilder,
  DocumentEvent,
  PipelineEventEmitter,
} from './pipeline.types.js';
